modules:
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.kde.okular
        - org.kde.kate
        - org.kde.yakuake
      remove:
        - org.kde.kmahjongg

    user: {}